### ISSUE TITLE
SelectInput component should expand to width of largest label text

### ISSUE THREAD

**Issue by nickj-rp** [palmetto/palmetto-components#157]
When assembling the `<SelectInput />` components into a horizontal layout it would be helpful if they would expand to the width of the longest option label value similar to how the html `<select>` element works.

Unless provided a specific width with css, they currently collapse like this:
![Screenshot from 2020-08-12 16-23-01](https://user-images.githubusercontent.com/60115137/90077897-27ea9680-dcb8-11ea-955e-556212f51b13.png)

Thanks!

**Comment by juanfabrega** [comment]
Hey @nickj-rp thanks for bringing this up. I will do a quick recon this morning and report back initial thoughts back on this issue.

**Comment by juanfabrega** [comment]
Hey @nickj-rp any chance you can provide a short code snippet so I can get an idea of the element that wraps these inputs and how its width is determined? Looks like maybe we're using a flex container from the layout but just want to make sure I understand the inner workings a bit better.

**Comment by juanfabrega** [comment]
@nickj-rp did some preliminary research on this and here are my current findings.

**Context** -- At the moment we are leveraging [react-select](https://github.com/JedWatson/react-select) for the `SelectInput` component.

**Findings**
Due to the multitude of features that react-select supports, it seems so far they have deemed this too complex a task since it has ripple effects on all the possible permutations of their component. There are a multitude of threads with this requested feature and subsequent discussion but I found this to be the most helpful:
https://github.com/JedWatson/react-select/issues/323

In the thread there are both reasons cited for the lack of support for this feature, but also some potential workarounds to implement. I attempted an implementation of two of these but sure enough, while they work properly in some instances they are brittle when it comes to supporting different use cases. E.G: supporting shifting position of the menu dropdown can easily break when moving to custom CSS for auto-width. 

Personally I am not a fan of NOT offering UX parity with vanilla HTML so I would love to actually get this working properly. I will leave this issue open, but it may take a few days until somebody can jump on this. With that said, I want to make sure that y'all are able to control width via a class for the time being, even if it is not super convenient. Hopefully we'll get this use case covered soon.

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SelectInput auto-width like native html select](https://trello.com/c/aKHxepcL/163-selectinput-auto-width-like-native-html-select)

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Styled browser/system select component alternative to react-select](https://trello.com/c/btrlfhgC/435-styled-browser-system-select-component-alternative-to-react-select)

**Comment by nathanyoung** [comment]
There is now a "native" select input available that should better handle this. 

https://ux.palmetto.com/?path=/docs/components-selectinputnative-overview--default-story

We will be issuing a PR to logistics-app to replace the existing `SelectInput` components with `SelectInputNative` where appropriate.
