### ISSUE TITLE
Contrast between copy and bg is low for danger Alert variant.

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#251]
<img width="534" alt="Screen Shot 2020-09-25 at 2 30 59 PM" src="https://user-images.githubusercontent.com/5695990/94318644-d59ac780-ff3d-11ea-8268-541e5fa3b69f.png">

**Comment by JCarmine** [comment]
For consideration:
![Uploading Screen Shot 2020-09-25 at 2.53.35 PM.png…]()

**Comment by JCarmine** [comment]
And from Material.

<img width="818" alt="Screen Shot 2020-09-26 at 8 51 04 PM" src="https://user-images.githubusercontent.com/5695990/94355584-07915400-003a-11eb-99e7-83c219d2592c.png">

**Comment by JCarmine** [comment]
Re-opening this. I honestly feel that the alert message should be stronger than its background. In the event that the app suffered a session-ending failure, I feel that the message should be bold, not subdued. 

Going forward, it might also be beneficial to issue a formal response when an issue is closed, to indicate that it was acknowledged, and also provide a justification for why it was disregarded.

<img width="811" alt="Screen Shot 2020-10-26 at 7 55 04 PM" src="https://user-images.githubusercontent.com/5695990/97252024-4ac01d80-17c6-11eb-9393-43c8387acc56.png">

**Comment by nathanyoung** [comment]
@JCarmine why reopened?

**Comment by nathanyoung** [comment]
@JCarmine weird, i just saw your explanation of why you reopened in my email, but wonder why it wasn't posted here. Going to blockquote it here:

> Re-opening this. I honestly feel that the alert message should be stronger than its background. In the event that the app suffered a session-ending failure, I feel that the message should be bold, not subdued.
> 
> Going forward, it might also be beneficial to issue a formal response when an issue is closed, to indicate that it was acknowledged, and also provide a justification for why it was disregarded.
> 
> ![](https://user-images.githubusercontent.com/5695990/97252024-4ac01d80-17c6-11eb-9393-43c8387acc56.png)







Anyways, the referenced PR #266 actually updated the tokens for the Alert to lighten the background, thus increasing the contrast up to WCAG AAA spec. Sorry, I didn't communicate that when closing. You can see that the danger Alert in the screenshot below is now more readable than what's in the original issue post.

If something needs to bold, like a failure, then use the `title` prop.

https://ux.palmetto.com/?path=/story/components-alert--with-icon

<img width="529" alt="Screen Shot 2020-10-28 at 7 18 04 AM" src="https://user-images.githubusercontent.com/1447339/97448279-ba7cf800-18ed-11eb-8027-a802f981c7ea.png">

I'm going to close this again because I believe your concerns have been addressed.
