### ISSUE TITLE
Components not compatible with Next.js SSR

### ISSUE THREAD

**Issue by mtblanton** [palmetto/palmetto-components#342]
![image](https://user-images.githubusercontent.com/2118649/100674542-eb0be380-332a-11eb-927e-6d66d7f40d65.png)

I _think_ this is coming from the Box component using `useBreakpoint`, which uses `useWindowSize`

full error from Next error reporter
```
Server Error

ReferenceError: window is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
Object.<anonymous>
file:/Users/taylorblanton/Repos/palmetto-website/node_modules/@palmetto/palmetto-components/dist/index.js (2:464)
Module._compile
internal/modules/cjs/loader.js (1138:30)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1158:10)
Module.load
internal/modules/cjs/loader.js (986:32)
Function.Module._load
internal/modules/cjs/loader.js (879:14)
Function.wrappedLoad [as _load]
file:/Users/taylorblanton/Repos/palmetto-website/node_modules/newrelic/lib/shimmer.js (373:24)
Module.require
internal/modules/cjs/loader.js (1026:19)
require
internal/modules/cjs/helpers.js (72:18)

external%20%22@palmetto/palmetto-components%22 (1:0) @ eval

> 1 | module.exports = require("@palmetto/palmetto-components");

Call Stack
Object.@palmetto/palmetto-components
file:/Users/taylorblanton/Repos/palmetto-website/.next/server/pages/palmetto-protect.js (325:1)
```

**Comment by nathanyoung** [comment]
@mtblanton i just made this codesandbox with nextjs to see if it would work and it and it does. 

https://codesandbox.io/s/withered-surf-4lyn6?file=/pages/index.js

Is there something I'm missing?

**Comment by nathanyoung** [comment]
> @mtblanton i just made this codesandbox with nextjs to see if it would work and it and it does.
> 
> https://codesandbox.io/s/withered-surf-4lyn6?file=/pages/index.js
> 
> Is there something I'm missing?

never mind, it stopped working and is now producing a similar error. Must of been cached or something.

**Comment by juanfabrega** [comment]
@nathanyoung @ericyliu none of our components explicitly use the window object, but it is used implicitly in some dependencies. An example of this is popovers, which will adjust their location based on the window position to ensure there is no cutoff. Because usage of the window object isn't really something we want to live without (since we are wanting to create breakpoint hooks and other utilities, for example) then I'd suggest using next's dynamic import feature to ensure that this code gets run on the client side. and not at compile time.

Here is an example importing the button.

const Button = dynamic(() =>
  import("@palmetto/palmetto-components").then((mod) => mod.Button)
);

The syntax is a bit `meh` but perhaps there is an abstraction we can use to make this more palatable (and export multiple components at a time).

Here is the codesandbox as well: https://codesandbox.io/s/bold-star-mymqz?file=/pages/index.js

I'm not intimately familiar with how nextJS dynamic imports work or what trade-offs we're making here so lets hasve a discussion and see if this works moving forward.

**Comment by mtblanton** [comment]
We're using a dynamic import now but this won't work for us in the long run. It prevents server-side rendering for the dynamic components, which was the reason we're using Next!

**Comment by nathanyoung** [comment]
@juanfabrega @mtblanton is this still an issue? Can we close?

**Comment by nathanyoung** [comment]
since there is a workaround, going to close this. re-open if this is something that still needs to be addressed.
