### ISSUE TITLE
Button variant="naked" doesn't allow any styling

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#359]
Repro: https://codesandbox.io/s/great-bardeen-9mmrp?file=/src/App.js

<img width="943" alt="Screen Shot 2020-12-10 at 8 16 04 AM" src="https://user-images.githubusercontent.com/1447339/101798458-f3e57d80-3abf-11eb-9a98-4beb414a9ad1.png">

**Comment by osbornm** [comment]
I was looking at this and the issue is because the `naked` class ends up with less specificity than `p-5xl` or `background-color-primary-500`.  [`0010` vs `0020`](https://speakerdeck.com/osbornm/css-less-and-the-new-ui?slide=27) respectively. So you _can_ style some properties just nothing that the [`naked` class sets](https://github.com/palmetto/palmetto-components/blob/main/src/components/Button/Button.module.scss#L53-L59)

A possible fix would be to rewrite how the `naked` buttons gets style so that it ends up not be a "sub-class" of button and is instead a sibling. 

IMHO this (hard to get specificity) is a common problem with utility classes. I assume other component would suffer from similar issues but it might not be as common to want to use utility classes. What are the thoughts on the value of tackling this? Is this common?

**Comment by nathanyoung** [comment]
A work around for this is that we've been using the `<Box>` component's `as` prop to create buttons that we can style (almost) however we want. As an example:

https://github.com/palmetto/ux-alchemy-prototype/blob/2b71869808c6f7491dad64e82ae037f68be6a72a/src/dtc/views/Power.jsx#L65-L79

With that, perhaps we should remove this prop?
So we might

**Comment by RyanMacBern** [comment]
I'm running into the same issue. We'd like the Palmetto App to use `<Button isNaked>` for clickable items that require custom styling. This is very difficult with the current implementation since it creates a high CSS specificity as well as including an inner span element:
```
<button class="button naked"><span class="label">{children}</span></button>
```
this requires CSS to be applied very specifically:
```
.customButton.customButton > span {
  // custom styles
}
```
My proposed solution is to not apply any styles with the naked class and to remove the inner span:
https://github.com/palmetto/palmetto-components/pull/624
