### ISSUE TITLE
Box hover states

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#428]
Allow hover states to be set on Box components

- background color
- color
- cursor
- transition timing?

Here's some inspiration
https://twitter.com/antfu7/status/1370173736456835076

**Comment by juanfabrega** [comment]
Hey @nathanyoung I very much want to go the tailwind route with this one and to that effect I've been researching ways to allow our users to properly purge unused css classes from their bundles. I would say that work precludes this one since without it, adding all the modifier utility classes is non-viable for production releases unfortunately.

**Comment by juanfabrega** [comment]
Just created one --https://trello.com/c/7LTxtYTS/551-review-purgecss-solutions-to-allow-growth-of-utility-class-system

**Comment by juanfabrega** [comment]
https://github.com/palmetto/palmetto-components/pull/439
