### ISSUE TITLE
Add an inputProps property for form controls

### ISSUE THREAD

**Issue by adepatie** [palmetto/palmetto-components#479]
Adding an `inputProps` property to form controls (i.e. TextField, SelectInput) would allow for support of form libraries such as [react-hook-form](https://react-hook-form.com/). This prop would take an object and spread (...) that object over the input element. 

i.e.
````javascript
  const { register } = useForm();
  return <TextField
    id="addressLine1"
    inputProps={{
      ...register("addressLine1")
    }}
  />
````

in palmetto-components/.../TextField.tsx
````javascript
  const { inputProps: restInputProps } = props;
  const inputProps = {
    /////
    ...restInputProps
  }
  ////
  return <input {...inputProps} />
  // repeat for other inputs (i.e. Cleave)

**Comment by juanfabrega** [comment]
hey @adepatie FYI with our latest release we have an `inputProps` interface for the `TextInput` component. This is by no means a complete solution to the issue but figured I'd let you know and perhaps you can test usage locally to ensure it is what you need.

NOTE: in order to not disturb too much with the existing component API, I decided to spread the input props at the top of the object rather than at the end, so that users can't override some of the top-level TextInput props that go in there. 

We can revisit this in the future as we continue to work on this.

LINK: https://www.npmjs.com/package/@palmetto/palmetto-components/v/0.74.5

**Comment by adepatie** [comment]
You are the man! Thank you Juan. I'll close this feature since the real problem that I hope we can solve is support for both controlled and uncontrolled components. I've been working a bit on allowing for this but I have had to prioritize other sprint work. I'll update the other issue I created to be more specific to that and provide context on some of the other challenges in doing so.
