### ISSUE TITLE
Box direction value 'row-reverse' doesn't work

### ISSUE THREAD

**Issue by mtblanton** [palmetto/palmetto-components#483]
setting a Box to row-reverse sets the class on the Box properly but the utility class doesn't exist in the CSS.

`<Box direction="row-reverse" />`

**Comment by juanfabrega** [comment]
Hey @mtblanton thanks for catching this! Updated release coming soon!

**Comment by juanfabrega** [comment]
Hey @mtblanton While I was working on this I realized the reason these classes did not get implemented originally (although we made a mistake in the docs including these options). It is because at the time (and still) we didn't have a way to support the responsiveness of these reverse directions, along with the childGap prop.

The childGap prop, adds a margin class to all the nodes and figures out the direction of that margin based on the direction of the flex container. As a part of this we exclude the last children node since we only want the childGap in between each of the children and no margin at the end.

However, this ends up breaking with row/column-reverse since the children nodes are still in the same order, they are just reversed for display purposes in the browser. So in this case we end up with a first node that visually has no childGap and looks kinda funky.

We had purposely tried to avoid JS resize listeners to the box and just use responsive utilities but this is one of the downsides since we can adjust those classes on the fly, they are added statically to each element.

Still thinking through an alternative here and will keep you posted.

**Comment by juanfabrega** [comment]
@mtblanton the most likely path forward (in the short term) is I will expose these classes and include a caveat in the docs that reversing rows/columns is incompatible with child gap. The escape hatch in child gap is super easy and intuitive (just add the margins individually in each child) so I’m not too worried.

**Comment by juanfabrega** [comment]
https://github.com/palmetto/palmetto-components/pull/492

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Minor bugs](https://trello.com/c/6KAmKTHK/685-minor-bugs)

**Comment by mtblanton** [comment]
@juanfabrega i missed your responses to this! That solution sounds good to me, hopefully gap for flex is supported in all browsers soon!
