### ISSUE TITLE
DateInput component's Datepicker should close Popover on date selection.

### ISSUE THREAD

**Issue by marciaga** [palmetto/palmetto-components#496]
I expected the Popover to close when a date is tapped in the DatePicker. If keeping the Popover open after date selection is the desired behavior, feel free to close this issue, thanks!

**Comment by juanfabrega** [comment]
Hey @marciaga perhaps this is something that can be improved, but the reason it doesn't close is because the datepicker allows range selection.

I'm thinking we can leave that up to the user and maybe pass a prop to close when a single date is selected (if the user isn't picking a range).

Open to other solutions, let me know what you think.

**Comment by marciaga** [comment]
Yeah, I think the expectation is that if the input isn't being purposed for a date range, then selecting one date should close the picker. A prop to allow this type of use case would be great!

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Popover should close on date select if not selecting range.](https://trello.com/c/1wvmOh5g/839-popover-should-close-on-date-select-if-not-selecting-range)

**Comment by juanfabrega** [comment]
https://github.com/palmetto/palmetto-components/pull/560
