### ISSUE TITLE
Update accepted type for Box css properties to allow for css vars to enable theming

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#765]
Can we eliminate the use of a css class while still maintaining "theming" like @RyanMacBern suggests below?

If we update the type for `borderColor` to ```borderColor?: BrandColor | `var(${string})`;```, then we could do
```suggestion
          <Box
            alignItems="flex-end"
            justifyContent="center"
            padding="md lg"
            borderWidth="0 0 xs 0"
            borderColor="var(--drawer-header-border-color, var(--color-brand-grey-100))"
```

_Originally posted by @RyanMacBern in https://github.com/palmetto/palmetto-components/pull/752#discussion_r854518107_

**Comment by juanfabrega** [comment]
@nathanyoung I am good with this in theory, but I'd advise reviewing the current logic on `Box`, since the borderColor actually will generate utility classes based on its value.  Moreover it is used in focus and hover stateful classes as well. So taking in css variables would involve changing this considerably to validate what kind of value we're getting and then push it into the Box accordingly.

**Comment by nathanyoung** [comment]
Agree, I think this would be fairly big undertaking unless I'm missing something. That's why I created this as an issue to discuss!

**Comment by mtblanton** [comment]
At this point why not just do a string type? You can iterate through your available colors to check if it matches one of those (you can probably map through the design tokens JSON for something like this) and if it doesn't match one of those set the style to the string.
